# Adding a user
POST http://localhost:3001/auth/signUp
Content-Type: application/json

{
  "email": "tester2@test.com",
  "password": "supperPassword123",
  "name": "Mr Tester"
}

###
# Adding an admin user
POST http://localhost:3001/auth/signUp
Content-Type: application/json

{
  "email": "tester3@test.com",
  "password": "supperPassword123",
  "name": "Mr Admin",
  "role": "Admin"
}
