version: '3'

name: jwt-smith-playground

services:
  jwt-smith-db:
    image: 'postgres:latest'
    container_name: 'jwt-smith-db'
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - ${PWD}/volumes/db-data/:/var/lib/postgresql/data/

  jwt-smith-admin:
    image: dpage/pgadmin4
    container_name: 'jwt-smith-admin'
    ports:
      - 9000:80
    env_file:
      - .env
    depends_on:
      - jwt-smith-db
    networks:
      - postgres-network
    volumes:
      - ${PWD}/volumes/pgadmin-data/:/var/lib/pgadmin/

  verdaccio-registry:
    image: verdaccio/verdaccio:latest
    container_name: verdaccio-registry
    networks:
      - npm-network
    ports:
      - '4873:4873'
    volumes:
      - ./config:/verdaccio/conf
      - storage:/verdaccio/storage
      - plugins:/verdaccio/plugins

networks:
  postgres-network:
    driver: bridge
  npm-network:
    driver: bridge
