name: Publish to npm

on:
  workflow_dispatch: # Manual trigger only

jobs:
  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 22] # Test on Node.js versions 18, 20, and 22
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test

  publish:
    name: Publish to npm
    needs: unit-test # Runs only if tests pass
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Check for changesets
        run: |
          if [ ! -d ".changeset" ] || [ -z "$(ls -A .changeset)" ]; then
            echo "No changesets found. Cannot publish."
            exit 1
          fi

      - name: Version bump (using changesets)
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          npx changeset version
          git add .
          git commit -m "Version bump via changesets" || echo "No version changes"
          git push

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx changeset publish

      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: NPM Deployment
          SLACK_USERNAME: JWT Smith
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: '✅ *JWT Smith* successfully published to npm!'

      - name: Notify Discord
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: '✅ *JWT Smith* successfully published to npm!'

  notify:
    name: Notify Slack
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Notify on Success
        if: success()
        uses: slackapi/slack-github-action@v1
        with:
          channel-id: '#your-channel'
          slack-message: '✅ Deployment Successful! 🚀'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_ICON: 'https://yourdomain.com/logo.png'

      - name: Notify on Failure
        if: failure()
        uses: slackapi/slack-github-action@v1
        with:
          channel-id: '#your-channel'
          slack-message: '🚨 Deployment Failed! Check logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_ICON: 'https://yourdomain.com/logo.png'
